### ISSUE TITLE
Setup credo and/or elixir formatter

### ISSUE THREAD

**Issue by PragTob** [elixir-bench/elixir-bench-api#12]
In recent PRs lots of my comments were code style related. We can automate that with either the elixir formatter or credo or both.

We should first get currently open PRs merged and then fix the offenses - otherwise it's a mess.

**Comment by tallysmartins** [comment]
I didn't get what "setup" really means. Adds a format check to the build scripts or just setup our settings and run it in the code and then send a PR? 

Another thing is that I thought about slicing the changes according to the amount of code affected by the formatetr, I ended with 9 parts of the code. We could start with the tests as I am going to write some more of them in the next tasks.

I also took a look in the ```.formatter.exs``` config file that already existed and changed the default line lenght value to 98, it was 120 and created the slices there, with commented lines that sets the input folders we want to target in each PR.

```
inputs: ["mix.exs", "{test}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test,lib/elixir_bench/benchmarks}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test,lib/elixir_bench/benchmarks,lib/elixir_bench/github}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test,lib/elixir_bench}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test,lib/elixir_bench,lib/elixir_bench_web/controllers}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test,lib/elixir_bench,lib/elixir_bench_web/controllers,lib/elixir_bench_web/schema}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,test,lib/elixir_bench,lib/elixir_bench_web/controllers,lib/elixir_bench_web/schema,lib/elixir_bench_web/views}/**/*.{ex,exs}"],
  #inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
```

**Comment by PragTob** [comment]
Sounds good thanks :)

I'm not really sure what "setup" means either :D I think you can let it run in CI I'm not sure how atm as I never set it up myself. You can check though there should be a cli option for that. Just in case I'm ccing @devonests he knows that stuff :D
